class SpeechText:
    WELCOME = "Bienvenue dans Heures de Prière!"
    WHAT_DO_YOU_WANT = "Que puis-je faire pour vous?"
    NOTIFY_MISSING_PERMISSIONS = "Pour utiliser cette fonctionnalité, vous devez autoriser l'accès à votre localisation dans l'application Alexa."
    NO_LOCATION = "Je n'ai pas pu obtenir votre localisation. Veuillez vérifier vos paramètres de localisation dans l'application Alexa."
    ERROR = "Désolé, une erreur s'est produite. Veuillez réessayer!"
    LOCATION_FAILURE = "Je n'ai pas pu obtenir votre localisation. Veuillez vérifier vos paramètres de localisation et réessayer."
    HELP_TEXT = "Vous pouvez me demander les heures de prière ou configurer des notifications de prière. Par exemple, essayez de dire : quelles sont les heures de prière?"
    FALL_BACK_TEXT = "Désolé, je n'ai pas compris. Veuillez réessayer."
    NOTIFICATION_SETUP_TEXT = "J'ai configuré les notifications pour les heures de prière. Vous recevrez une notification avant chaque prière."
    GOODBYE = "Au revoir!"
