name: Deploy Alexa Skill

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Set up ASK CLI
        run: |
          npm install -g ask-cli
          mkdir -p ~/.ask
          echo '{
            "profiles": {
              "default": {
                "token": {
                  "access_token": "${{ secrets.ASK_ACCESS_TOKEN }}",
                  "refresh_token": "${{ secrets.ASK_REFRESH_TOKEN }}",
                  "token_type": "bearer",
                  "expires_in": 3600
                },
                "vendor_id": "${{ secrets.ASK_VENDOR_ID }}",
                "skill_id": "${{ secrets.SKILL_ID }}"
              }
            }
          }' > ~/.ask/cli_config

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Deploy
        run: make deploy
